import admin from 'firebase-admin';
import { db } from '../config/firebase.js';
import { adminService } from '../services/adminService.js';
import logger from '../config/logger.js';

/**
 * Middleware to require admin role for protected routes.
 *
 * SECURITY FIX (S9): Supports TWO authentication pathways:
 *   1. Admin OTP session tokens (generated by adminService.verifyOTP)
 *   2. Firebase ID tokens with an admin role in Firestore
 *
 * The OTP path is checked first because the admin panel uses it exclusively.
 */
export const requireAdmin = async (req, res, next) => {
    try {
        // Extract token from Authorization header
        const authHeader = req.headers.authorization;

        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            return res.status(401).json({ error: 'Unauthorized: No token provided' });
        }

        const token = authHeader.split('Bearer ')[1];

        // ── Path 1: Admin OTP session token ──────────────────────────
        const session = await adminService.validateSessionAsync(token);
        if (session.valid) {
            req.user = { uid: session.email, role: 'admin', email: session.email };
            req.adminEmail = session.email;
            logger.info(`Admin access granted via OTP session to ${session.email}`);
            return next();
        }

        // ── Path 2: Firebase ID token ────────────────────────────────
        let decoded;
        try {
            decoded = await admin.auth().verifyIdToken(token);
        } catch (error) {
            logger.warn('Invalid admin token (neither OTP session nor Firebase):', error.message);
            return res.status(401).json({ error: 'Unauthorized: Invalid token' });
        }

        // Get user document to check role
        const userSnapshot = await db.collection('users')
            .where('walletAddress', '==', decoded.uid)
            .limit(1)
            .get();

        if (userSnapshot.empty) {
            // Check by email as fallback
            const emailSnapshot = await db.collection('users')
                .where('email', '==', decoded.email)
                .limit(1)
                .get();

            if (emailSnapshot.empty) {
                return res.status(403).json({ error: 'Forbidden: User not found' });
            }

            const userData = emailSnapshot.docs[0].data();
            if (userData.role !== 'admin') {
                return res.status(403).json({ error: 'Forbidden: Admin access required' });
            }

            req.user = { uid: decoded.uid, role: 'admin', ...userData };
            req.adminEmail = decoded.email;
            return next();
        }

        const userData = userSnapshot.docs[0].data();

        // Check if user has admin role
        if (userData.role !== 'admin') {
            logger.warn(`Access denied for non-admin user: ${decoded.uid}`);
            return res.status(403).json({ error: 'Forbidden: Admin access required' });
        }

        // Attach user data to request
        req.user = { uid: decoded.uid, role: 'admin', ...userData };
        req.adminEmail = decoded.email;

        // Log admin action
        logger.info(`Admin access granted via Firebase token to ${decoded.email || decoded.uid}`);

        next();
    } catch (error) {
        logger.error('Error in requireAdmin middleware:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
};

export default requireAdmin;
